In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("X_train.csv")
dataset.shape

(1460, 84)

In [4]:
dataset.head()

,Id,SalePrice,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,12.247694,0.235294,0.75,0.418208,0.366344,1.0,1.0,0.000000,0.333333,...,1.0,1.0,0.0,0.090909,0.50,0.666667,0.75,0.0,0.0,0.0
1,2,12.109011,0.000000,0.75,0.495064,0.391317,1.0,1.0,0.000000,0.333333,...,1.0,1.0,0.0,0.363636,0.25,0.666667,0.75,0.0,0.0,0.0
2,3,12.317167,0.235294,0.75,0.434909,0.422359,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,0.727273,0.50,0.666667,0.75,0.0,0.0,0.0
3,4,11.849398,0.294118,0.75,0.388581,0.390295,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,0.090909,0.00,0.666667,0.00,0.0,0.0,0.0
4,5,12.429216,0.235294,0.75,0.513123,0.468761,1.0,1.0,0.333333,0.333333,...,1.0,1.0,0.0,1.000000,0.50,0.666667,0.75,0.0,0.0,0.0

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(dataset.drop(columns=['SalePrice']),dataset['SalePrice'],test_size=0.1,random_state=0)

In [24]:
X_test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
529,530,0.000000,0.75,0.440313,0.630999,1.0,1.0,0.333333,0.333333,1.0,...,1.0,1.0,0.0,0.181818,0.25,0.666667,0.25,1.0,1.0,0.0
491,492,0.176471,0.75,0.490408,0.389061,1.0,1.0,0.000000,0.333333,1.0,...,0.5,1.0,0.0,0.636364,0.00,0.666667,0.75,0.0,0.0,0.0
459,460,0.176471,0.75,0.440313,0.329918,1.0,1.0,0.333333,0.000000,1.0,...,1.0,1.0,0.0,0.545455,0.75,0.666667,0.75,1.0,0.0,0.0
279,280,0.235294,0.75,0.508690,0.399404,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.0,0.181818,0.50,0.666667,0.75,0.0,0.0,0.0
655,656,0.823529,0.25,0.000000,0.050188,1.0,1.0,0.000000,0.333333,1.0,...,1.0,1.0,0.0,0.181818,1.00,0.666667,0.50,0.0,0.0,0.0

In [25]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [26]:
print(reg.intercept_)
print(reg.coef_)

9.239510938151117
[-1.58874628e-05 -1.42768541e-02  8.13802041e-02  4.51991960e-03
  2.57253973e-01  1.93741013e-01  2.50669878e-02 -6.57448763e-04
  5.06416175e-02  3.24570806e-01  2.08667086e-02 -6.82240816e-03
  2.26423435e-01  6.64416410e-02  1.01342359e-01 -8.25753079e-03
 -1.46952657e-02  4.81200986e-01  3.06699624e-01 -8.29199606e-02
 -2.91034682e-02  4.37657123e-03 -6.79340196e-02  1.03198480e-01
 -5.55069643e-02  1.32591075e-02  3.70321867e-02  2.74629678e-02
  5.06433146e-02  4.64978497e-02  6.26596423e-02  2.33567704e-02
  4.84367810e-02 -2.70651388e-03  1.11582945e-01  3.68103714e-02
  6.47968669e-02 -4.99554385e-02  9.96053711e-02  1.42343824e-02
  4.33337182e-02  4.90820362e-02 -1.84569076e-02  5.24427854e-01
  1.54189188e-01  7.82001921e-02  6.37918914e-01  1.44688475e-01
  4.86461908e-02  5.32511422e-02  4.14737077e-02 -4.78450980e-02
 -1.43904255e-01  8.36171926e-02  6.25964011e-02  1.13949861e-01
  4.16309616e-02  2.14051278e-02 -3.89705790e-02  6.75942468e-02
  1.90436785e-02  1.26448936e-01  7.11571373e-02  1.00922546e-01
  6.63558619e-02  1.63798459e-02  6.95262946e-02  9.91181040e-03
  8.14436851e-02  7.52942253e-02  1.69400193e-01  3.54596826e+00
 -3.01402330e+00  2.37914663e-02 -5.30655474e-04  1.24893889e-01
 -1.21852178e-02 -1.75352481e-02  3.72303235e-03  1.19363197e-01
 -5.07210620e-03 -5.48754238e-04  1.25611128e-01]

In [27]:
#making a predicted y value for given X
y_pred=reg.predict(X_test)

In [28]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

         Actual  Predicted
529   12.209188  12.182349
491   11.798104  11.913904
459   11.608236  11.697882
279   12.165251  12.296613
655   11.385092  11.415668
...         ...        ...
1452  11.884489  11.771880
113   12.287653  12.297787
1282  11.921718  12.015764
1163  11.598727  11.767662
310   12.017331  12.046903

[146 rows x 2 columns]

In [29]:
from sklearn.metrics import mean_squared_error,r2_score
print('MSE:%.2f'%mean_squared_error(y_test,y_pred))
print('R2_score:%.2f'%r2_score(y_test,y_pred))

MSE:0.02
R2_score:0.87